### ISSUE TITLE
Unclear if IRB approval is necessary for review

### ISSUE THREAD

**Issue by poojasidney** [fcps/research-request#13]
The documentation for research request proposal requests states that researchers should "Provide a copy of your IRB application. Provide an IRB approval letter or statement that IRB approval is pending FCPS approval." In the online submission system, the question "Has this proposal been approved by your IRB?" has the options "no", "yes conditional on FCPS approval", and "yes not conditional on FCPS approval". It is unclear whether my application will be considered in a situation in which IRB approval from my institution is necessary, but my institution will not review it without FCPS approval. It is also unclear whether a letter is necessary in this case.

**Comment by wbuchanan** [comment]
@fcpsswang 
Can you work on some sample verbiage that we can add to the document to clarify the process based on the issue above?  In short we need to make it clear in this document that IRB approval can be contingent on FCPS approval and the research request form provides a field to indicate that.  Approval of FCPS as a requisite for IRB approval is not a disqualifying factor.

**Comment by wbuchanan** [comment]
Need to check the punctuation in the updated line.  It may be useful to add a child `<ul>` element to enumerate the different scenarios more clearly.

**Comment by wbuchanan** [comment]
Did the changes get pushed into the `gh-pages` branch as well?  If not you need to push the changes there from master so they will appear when the webpage is rendered.

**Comment by fcpsswang** [comment]
This issue can be closed.
